version: '3'

services:
  app:
    image: ${IMAGE_NAME}:latest
    ports:
      - "4040:4040"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    networks:
      - furkan-network

networks:
  furkan-network:
    driver: bridge
