version: '3'

services:
  app:
    image: ${IMAGE_NAME}:latest
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    networks:
      - furkan-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_reverse_proxy.conf.j2:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - furkan-network

networks:
  furkan-network:
    driver: bridge
